def calculate_conflicts(x,y):
    if((x=="Metformin" and y=="Brexpiprazole")
       or (x=="Metformin" and y=="Oseltamivir")
       or (x=="Metformin" and y=="Zanamivir")
       or (x=="Metformin" and y=="Doxycycline")
       or (x=="Metformin" and y=="Fluticasone")
       or (x=="Metformin" and y=="Arformoterol")
       or (x=="Metformin" and y=="Aclidinium")
       or (x=="Metformin" and y=="Ceftriaxone")
       or (x=="Metformin" and y=="Ceftazidime")
       or (x=="Metformin" and y=="Atorvastatin")
       or (x=="Metformin" and y=="Niacin")
       or (x=="Metformin" and y=="Bumetanide")
       or (x=="Aducanumab" and y=="Mepolizumab")
       or (x=="Aducanumab" and y=="Benralizumab")
       or (x=="Nateglinide" and y=="Donepezil")
       or (x=="Nateglinide" and y=="Memantine")
       or (x=="Nateglinide" and y=="Atorvastatin")
       or (x=="Nateglinide" and y=="Lisinopril") 
       or (x=="Nateglinide" and y=="Aclidinium") 
       or (x=="Nateglinide" and y=="Ceftriaxone")
       or (x=="Nateglinide" and y=="Ceftazidime")
       or (x=="Nateglinide" and y=="Arformoterol")
       or (x=="Nateglinide" and y=="Cefotaxime")
       or (x=="Nateglinide" and y=="Galantamine") 
       or (x=="Lecanemab" and y=="Mepolizumab") 
       or (x=="Lecanemab" and y=="Benralizumab")
       or (x=="Donepezil" and y=="Levomenthol")
       or (x=="Donepezil" and y=="Arformoterol")
       or (x=="Donepezil" and y=="Fluticasone")
       or (x=="Donepezil" and y=="Galantamine")
       or (x=="Memantine" and y=="Fluvoxamine")
       or (x=="Memantine" and y=="Canagliflozin")
       or (x=="Memantine" and y=="Doxycycline")
       or (x=="Memantine" and y=="Arformoterol")
       or (x=="Memantine" and y=="Fluticasone")
       or (x=="Memantine" and y=="Cefotaxime")
       or (x=="Memantine" and y=="Ceftriaxone")
       or (x=="Memantine" and y=="Ceftazidime")
       or (x=="Brexpiprazole" and y=="Nitroglycerin")
       or (x=="Brexpiprazole" and y=="Lisinopril")
       or (x=="Brexpiprazole" and y=="Ramipril")
       or (x=="Brexpiprazole" and y=="Enalapril")
       or (x=="Brexpiprazole" and y=="Galantamine")
       or (x=="Fluoxetine" and y=="Aclidinium")
       or (x=="Fluvoxamine" and y=="Oseltamivir")
       or (x=="Fluvoxamine" and y=="Zanamivir")
       or (x=="Fluvoxamine" and y=="Choline Salicylate")
       or (x=="Fluvoxamine" and y=="Doxycycline")
       or (x=="Fluvoxamine" and y=="Aclidinium")
       or (x=="Fluvoxamine" and y=="Lisnopril")
       or (x=="Fluvoxamine" and y=="Ceftazidime")
       or (x=="Fluvoxamine" and y=="Cefotaxime")
       or (x=="Fluvoxamine" and y=="Ceftriaxone")
       or (x=="Citalopram" and y=="Dihydroergocristine")
       or (x=="Oseltamivir" and y=="Canagliflozin")
       or (x=="Oseltamivir" and y=="Doxycycline")
       or (x=="Oseltamivir" and y=="Choline Salicylate")
       or (x=="Oseltamivir" and y=="Lisinopril")
       or (x=="Oseltamivir" and y=="Aclidinium")
       or (x=="Oseltamivir" and y=="Arformoterol")
       or (x=="Oseltamivir" and y=="Ceftazidime")
       or (x=="Zanamivir" and y=="Ceftazidime")
       or (x=="Zanamivir" and y=="Cefotaxime")
       or (x=="Zanamivir" and y=="Canagliflozin")
       or (x=="Zanamivir" and y=="Choline Salicylate")
       or (x=="Zanamivir" and y=="Doxycycline")
       or (x=="Zanamivir" and y=="Lisinopril")
       or (x=="Zanamivir" and y=="Arformoterol")
       or (x=="Zanamivir" and y=="Ceftriaxone")
       or (x=="Bumetanide" and y=="Ramipril")
       or (x=="Bumetanide" and y=="Choline Salicylate")
       or (x=="Canagliflozin" and y=="Levomenthol")
       or (x=="Canagliflozin" and y=="Doxycycline")
       or (x=="Canagliflozin" and y=="Aclidinium")
       or (x=="Canagliflozin" and y=="Ceftriaxone")
       or (x=="Canagliflozin" and y=="Arformoterol")
       or (x=="Canagliflozin" and y=="Ceftazidime")
       or (x=="Canagliflozin" and y=="Cefotaxime")
       or (x=="Nitroglycerin" and y=="Ramipril")
       or (x=="Nitroglycerin" and y=="Enalapril")
       or (x=="Nitroglycerin" and y=="Lisonopril")
       or (x=="Nitroglycerin" and y=="Arformoterol")
       or (x=="Capsaicin" and y=="Fluticasone")
       or (x=="Choline Salicylate" and y=="Doxycycline")
       or (x=="Choline Salicylate" and y=="Aclidinium")
       or (x=="Choline Salicylate" and y=="Arformoterol")
       or (x=="Choline Salicylate" and y=="Ceftriaxone")
       or (x=="Choline Salicylate" and y=="Ceftazidime")
       or (x=="Choline Salicylate" and y=="Cefotaxime")
       or (x=="Levomenthol" and y=="Azithromycin")
       or (x=="Levomenthol" and y=="Ramipril")
       or (x=="Levomenthol" and y=="Enalapril")
       or (x=="Levomenthol" and y=="Lisinopril")
       or (x=="Levomenthol" and y=="Galantamine")
       or (x=="Azithromycin" and y=="Arformoterol")
       or (x=="Azithromycin" and y=="Galantamine")
       or (x=="Clarithromycin" and y=="Enalapril")
       or (x=="Clarithromycin" and y=="Arformoterol")
       or (x=="Doxycycline" and y=="Arformoterol")
       or (x=="Doxycycline" and y=="Cefotaxime")
       or (x=="Doxycycline" and y=="Aclidinium")
       or (x=="Doxycycline" and y=="Ceftriaxone")
       or (x=="Doxycycline" and y=="Ceftazidime")
       or (x=="Ramipril" and y=="Arformoterol")
       or (x=="Ramipril" and y=="Dihydroergocristine")
       or (x=="Enalapril" and y=="Arformoterol")
       or (x=="Enalapril" and y=="Dihydroergocristine")
       or (x=="Enalapril" and y=="Fluticasone")
       or (x=="Lisinopril" and y=="Dihydroergocristine")
       or (x=="Lisinopril" and y=="Aclidinium")
       or (x=="Lisinopril" and y=="Arformoterol")
       or (x=="Lisinopril" and y=="Ceftriaxone")
       or (x=="Lisinopril" and y=="Ceftazidime")
       or (x=="Lisinopril" and y=="Cefotaxime")
       or (x=="Lisinopril" and y=="Galantamine")
       or (x=="Fluticasone" and y=="Galantamine")
       or (x=="Aclidinium" and y=="Ceftriaxone")
       or (x=="Aclidinium" and y=="Ceftazidime")
       or (x=="Aclidinium" and y=="Cefotaxime")
       or (x=="Arformoterol" and y=="Ceftriaxone")
       or (x=="Arformoterol" and y=="Ceftazidime")
       or (x=="Arformoterol" and y=="Cefotaxime")
       or (x=="Arformoterol" and y=="Galantamine")
       or (x=="Hydroflumethiazide" and y=="Brexpiprazole")
       or (x=="Aliskiren" and y=="Bumetanide")
       or (x=="Aliskiren" and y=="Nitroglycerin")
       or (x=="Aliskiren" and y=="Canagliflozin")
       or (x=="Aliskiren" and y=="Levomenthol")
       or (x=="Cilazapril" and y=="Brexpiprazole")
       or (x=="Cilazapril" and y=="Bumetanide")
       or (x=="Prazosin" and y=="Bumetanide")
       or (x=="Levamlodipine" and y=="Atorvastatin")
       or (x=="Levamlodipine" and y=="Bumetanide")
       or (x=="Cilazapril" and y=="Nitroglycerin")
       or (x=="Cilazapril" and y=="Arformoterol")
       or (x=="Prazosin" and y=="Canagliflozin")
       or (x=="Cilazapril" and y=="Levomenthol")
       or (x=="Levamlodipine" and y=="Ramipril")
       or (x=="Levamlodipine" and y=="Enalapril")
       or (x=="Levamlodipine" and y=="Lisinopril")
       or (x=="Levamlodipine" and y=="Arformoterol")
       or (x=="Prazosin" and y=="Dihydroergocristine")
       or (x=="Cilazapril" and y=="Dihydroergocristine")
       or (x=="Levamlodipine" and y=="Dihydroergocristine")
       ):
        return 50
    
    if (
        (x=="Metformin" and y=="Paroxetine")
       or (x=="Metformin" and y=="Citalopram")
       or (x=="Metformin" and y=="Fluoxetine")
       or (x=="Metformin" and y=="Fluvoxamine")
       or (x=="Metformin" and y=="Escitalopram")
       or (x=="Metformin" and y=="Ramipril")
       or (x=="Metformin" and y=="Enalapril")
       or (x=="Metformin" and y=="Lisinopril")
       or (x=="Metformin" and y=="Choline Salicylate")
       or (x=="Insulin human" and y=="Paroxetine")
       or (x=="Insulin human" and y=="Fluvoxamine")
       or (x=="Insulin human" and y=="Fluoxetine")
       or (x=="Insulin human" and y=="Brexpiprazole")
       or (x=="Insulin human" and y=="Citalopram")
       or (x=="Insulin human" and y=="Bumetanide")
       or (x=="Insulin human" and y=="Escitalopram")
       or (x=="Insulin human" and y=="Niacin")
       or (x=="Insulin human" and y=="Canagliflozin") 
       or (x=="Insulin human" and y=="Choline Salicylate") 
       or (x=="Insulin human" and y=="Ramipril")
       or (x=="Insulin human" and y=="Enalapril")
       or (x=="Insulin human" and y=="Lisinopril")
       or (x=="Insulin human" and y=="Fluticasone")
       or (x=="Acarbose" and y=="Brexpiprazole") 
       or (x=="Acarbose" and y=="Fluoxetine") 
       or (x=="Acarbose" and y=="Fluvoxamine")
       or (x=="Acarbose" and y=="Paroxetine")
       or (x=="Acarbose" and y=="Citalopram")
       or (x=="Acarbose" and y=="Escitalopram")
       or (x=="Acarbose" and y=="Niacin")
       or (x=="Acarbose" and y=="Bumetanide")
       or (x=="Acarbose" and y=="Canagliflozin")
       or (x=="Acarbose" and y=="Choline Salicylate")
       or (x=="Acarbose" and y=="Fluticasone")
       or (x=="Nateglinide" and y=="Brexpiprazole")
       or (x=="Nateglinide" and y=="Fluoxetine")
       or (x=="Nateglinide" and y=="Fluvoxamine")
       or (x=="Nateglinide" and y=="Escitalopram")
       or (x=="Nateglinide" and y=="Citalopram")
       or (x=="Nateglinide" and y=="Niacin")
       or (x=="Nateglinide" and y=="Bumetanide")
       or (x=="Nateglinide" and y=="Choline Salicylate")
       or (x=="Nateglinide" and y=="Fluticasone")
       or (x=="Miglitol" and y=="Brexpiprazole")
       or (x=="Miglitol" and y=="Fluoxetine")
       or (x=="Miglitol" and y=="Fluvoxamine")
       or (x=="Miglitol" and y=="Escitalopram")
       or (x=="Miglitol" and y=="Paroxetine")
       or (x=="Miglitol" and y=="Citalopram")
       or (x=="Miglitol" and y=="Niacin")
       or (x=="Miglitol" and y=="Bumetanide")
       or (x=="Miglitol" and y=="Canagliflozin")
       or (x=="Miglitol" and y=="Choline Salicylate")
       or (x=="Miglitol" and y=="Fluticasone")
       or (x=="Donepezil" and y=="Citalopram")
       or (x=="Donepezil" and y=="Paroxetine")
       or (x=="Donepezil" and y=="Fluvoxamine")
       or (x=="Donepezil" and y=="Methocarbamol")
       or (x=="Donepezil" and y=="Niacin")
       or (x=="Donepezil" and y=="Escitalopram")
       or (x=="Donepezil" and y=="Aclidinium")
       or (x=="Donepezil" and y=="Fluoxetine")
       or (x=="Memantine" and y=="Citalopram")
       or (x=="Memantine" and y=="Paroxetine")
       or (x=="Memantine" and y=="Choline Salicylate")
       or (x=="Memantine" and y=="Bumetanide")
       or (x=="Memantine" and y=="Escitalopram")
       or (x=="Memantine" and y=="Aclidinium")
       or (x=="Brexpiprazole" and y=="Fluvoxamine")
       or (x=="Brexpiprazole" and y=="Paroxetine")
       or (x=="Brexpiprazole" and y=="Citalopram")
       or (x=="Brexpiprazole" and y=="Escitalopram")
       or (x=="Brexpiprazole" and y=="Fluoxetine")
       or (x=="Brexpiprazole" and y=="Niacin")
       or (x=="Brexpiprazole" and y=="Canagliflozin")
       or (x=="Brexpiprazole" and y=="Methocarbamol")
       or (x=="Brexpiprazole" and y=="Arformoterol")
       or (x=="Fluoxetine" and y=="Niacin")
       or (x=="Fluoxetine" and y=="Canagliflozin")
       or (x=="Fluoxetine" and y=="Capsaicin")
       or (x=="Fluoxetine" and y=="Methocarbamol")
       or (x=="Fluoxetine" and y=="Arformoterol")
       or (x=="Fluoxetine" and y=="Clarithromycin")
       or (x=="Fluoxetine" and y=="Galantamine")
       or (x=="Paroxetine" and y=="Atorvastatin")
       or (x=="Paroxetine" and y=="Niacin")
       or (x=="Paroxetine" and y=="Canagliflozin")
       or (x=="Paroxetine" and y=="Capsaicin")
       or (x=="Paroxetine" and y=="Methocarbamol")
       or (x=="Fluvoxamine" and y=="Niacin")
       or (x=="Fluvoxamine" and y=="Bumetanide")
       or (x=="Fluvoxamine" and y=="Canagliflozin")
       or (x=="Fluvoxamine" and y=="Levomenthol")
       or (x=="Fluvoxamine" and y=="Methocarbamol")
       or (x=="Fluvoxamine" and y=="Fluticasone")
       or (x=="Fluvoxamine" and y=="Arformoterol")
       or (x=="Fluvoxamine" and y=="Dihydroergocristine")
       or (x=="Fluvoxamine" and y=="Galantamine")
       or (x=="Fluvoxamine" and y=="Atorvastatin")
       or (x=="Citalopram" and y=="Atorvastatin")
       or (x=="Citalopram" and y=="Niacin")
       or (x=="Citalopram" and y=="Canagliflozin")
       or (x=="Citalopram" and y=="Capsaicin")
       or (x=="Citalopram" and y=="Levomenthol")
       or (x=="Citalopram" and y=="Methocarbamol")
       or (x=="Citalopram" and y=="Clarithromycin")
       or (x=="Citalopram" and y=="Arformoterol")
       or (x=="Citalopram" and y=="Galantamine")
       or (x=="Escitalopram" and y=="Niacin")
       or (x=="Escitalopram" and y=="Canagliflozin")
       or (x=="Escitalopram" and y=="Capsaicin")
       or (x=="Escitalopram" and y=="Levomenthol")
       or (x=="Escitalopram" and y=="Methocarbamol")
       or (x=="Escitalopram" and y=="Arformoterol")
       or (x=="Escitalopram" and y=="Galantamine")
       or (x=="Oseltamivir" and y=="Bumetanide")
       or (x=="Oseltamivir" and y=="Ceftriaxone")
       or (x=="Oseltamivir" and y=="Cefotaxime")
       or (x=="Zanamivir" and y=="Bumetanide")
       or (x=="Atorvastatin" and y=="Doxycycline")
       or (x=="Atorvastatin" and y=="Enalapril")
       or (x=="Atorvastatin" and y=="Fluticasone")
       or (x=="Atorvastatin" and y=="Dihydroergocristine")
       or (x=="Atorvastatin" and y=="Azithromycin")
       or (x=="Atorvastatin" and y=="Capsaicin")
       or (x=="Niacin" and y=="Azithromycin")
       or (x=="Niacin" and y=="Enalapril")
       or (x=="Niacin" and y=="Arformoterol")
       or (x=="Niacin" and y=="Dihydroergocristine")
       or (x=="Niacin" and y=="Galantamine")
       or (x=="Bumetanide" and y=="Enalapril")
       or (x=="Bumetanide" and y=="Doxycycline")
       or (x=="Bumetanide" and y=="Aclidinium")
       or (x=="Bumetanide" and y=="Lisinopril")
       or (x=="Bumetanide" and y=="Arformoterol")
       or (x=="Bumetanide" and y=="Cilastatin")
       or (x=="Bumetanide" and y=="Ceftriaxone")
       or (x=="Bumetanide" and y=="Ceftazidime")
       or (x=="Bumetanide" and y=="Cefotaxime")
       or (x=="Canagliflozin" and y=="Choline Salicylate")
       or (x=="Canagliflozin" and y=="Ramipril")
       or (x=="Canagliflozin" and y=="Enalapril")
       or (x=="Canagliflozin" and y=="Lisinopril")
       or (x=="Canagliflozin" and y=="Fluticasone")
       or (x=="Nitroglycerin" and y=="Dihydroergocristine")
       or (x=="Capsaicin" and y=="Azithromycin")
       or (x=="Capsaicin" and y=="Clarithromycin")
       or (x=="Capsaicin" and y=="Doxycycline")
       or (x=="Capsaicin" and y=="Aclidinium")
       or (x=="Capsaicin" and y=="Ceftriaxone")
       or (x=="Capsaicin" and y=="Ceftazidime")
       or (x=="Capsaicin" and y=="Cefotaxime")
       or (x=="Capsaicin" and y=="Dihydroergocristine")
       or (x=="Choline Salicylate" and y=="Ramipril")
       or (x=="Choline Salicylate" and y=="Enalapril")
       or (x=="Choline Salicylate" and y=="Lisinopril")
       or (x=="Azithromycin" and y=="Fluticasone")
       or (x=="Fluticasone" and y=="Dihydroergocristine")
       or (x=="Aclidinium" and y=="Galantamine")
       or (x=="Hydroflumethiazide" and y=="Acarbose")
       or (x=="Hydroflumethiazide" and y=="Metformin")
       or (x=="Hydroflumethiazide" and y=="Nateglinide")
       or (x=="Hydroflumethiazide" and y=="Insulin human")
       or (x=="Hydroflumethiazide" and y=="Miglitol")
       or (x=="Hydroflumethiazide" and y=="Memantine")
       or (x=="Hydroflumethiazide" and y=="Fluvoxamine")
       or (x=="Hydroflumethiazide" and y=="Fluoxetine")
       or (x=="Hydroflumethiazide" and y=="Paroxetine")
       or (x=="Hydroflumethiazide" and y=="Escitalopram")
       or (x=="Hydroflumethiazide" and y=="Citalopram")
       or (x=="Hydroflumethiazide" and y=="Oseltamivir")
       or (x=="Hydroflumethiazide" and y=="Zanamivir")
       or (x=="Hydroflumethiazide" and y=="Bumetanide")
       or (x=="Hydroflumethiazide" and y=="Nitroglycerin")
       or (x=="Hydroflumethiazide" and y=="Canagliflozin")
       or (x=="Hydroflumethiazide" and y=="Choline_salicylate")
       or (x=="Hydroflumethiazide" and y=="Ramipril")
       or (x=="Hydroflumethiazide" and y=="Doxycycline")
       or (x=="Hydroflumethiazide" and y=="Enalapril")
       or (x=="Hydroflumethiazide" and y=="Lisinopril")
       or (x=="Hydroflumethiazide" and y=="Fluticasone")
       or (x=="Hydroflumethiazide" and y=="Aclidinium")
       or (x=="Hydroflumethiazide" and y=="Arformoterol")
       or (x=="Hydroflumethiazide" and y=="Ceftazidime")
       or (x=="Hydroflumethiazide" and y=="Ceftriaxone")
       or (x=="Hydroflumethiazide" and y=="Arformoterol")
       or (x=="Aliskiren" and y=="Fluvoxamine")
       or (x=="Levamlodipine" and y=="Insulin human")
       or (x=="Levamlodipine" and y=="Metformin")
       or (x=="Levamlodipine" and y=="Nateglinide")
       or (x=="Levamlodipine" and y=="Acarbose")
       or (x=="Levamlodipine" and y=="Miglitol")
       or (x=="Cilazapril" and y=="Insulin human")
       or (x=="Cilazapril" and y=="Metformin")
       or (x=="Cilazapril" and y=="Choline Salicylate")
       or (x=="Levamlodipine" and y=="Paroxetine")
       or (x=="Levamlodipine" and y=="Clarithromycin")
       or (x=="Levamlodipine" and y=="Nitroglycerin")
       or (x=="Prazosin" and y=="Nitroglycerin")
       or (x=="Prazosin" and y=="Choline Salicylate")
       or (x=="Cilazapril" and y=="Canagliflozin")
       or (x=="Levamlodipine" and y=="Canagliflozin")
       or (x=="Levamlodipine" and y=="Capsaicin")
       or (x=="Levamlodipine" and y=="Fluticasone")
       or (x=="Prazosin" and y=="Ramipril")
       or (x=="Cilazapril" and y=="Ramipril")
       or (x=="Prazosin" and y=="Enalapril")
       or (x=="Cilazapril" and y=="Enalapril")
       or (x=="Prazosin" and y=="Lisinopril")
       or (x=="Prazosin" and y=="Arformoterol")
       or (x=="Cilazapril" and y=="Lisinopril")
    ):
        return 100
    
    if((x=="Nateglinide" and y=="Paroxetine")
         or (x=='Donepezil' and y=='Clarithromycin')
         or (x=='Memantine' and y=='Fluoxetine')
         or (x=='Brexpiprazole' and y=='Dihydroergocristine')
         or (x=='Paroxetine' and y=='Arformoterol')
         or (x=='Paroxetine' and y=='Clarithromycin')
         or (x=='Paroxetine' and y=='Aclidinium')
         or (x=='Paroxetine' and y=='Galantamine')
         or (x=='Fluvoxamine' and y=='Capsaicin')
         or (x=='Fluvoxamine' and y=='Clarithromycin')
         or (x=='Escitalopram' and y=='Aclidinium')
         or (x=='Escitalopram' and y=='Clarithromycin')
         or (x=='Canagliflozin' and y=='Clarithromycin')
         or (x=='Levomenthol' and y=='Clarithromycin')
         or (x=='Azithromycin' and y=='Dihydroergocristine')
         or (x=='Clarithromycin' and y=='Dihydroergocristine')
         or (x=='Clarithromycin' and y=='Fluticasone')
         or (x=='Clarithromycin' and y=='Galantamine')
         or (x=='Arformoterol' and y=='Dihydroergocristine')
         or (x=='Aliskiren' and y=='Clarithromycin')
         or (x=='Aliskiren' and y=='Ramipril')
         or (x=='Aliskiren' and y=='Enalapril')
         or (x=='Aliskiren' and y=='Lisinopril')
         or (x=='Prazosin' and y=='Brexpiprazole')
         ):
        return 500
    
    else:
        return 0
    
def get_statement(i):
    if i==0:
        return "Perfectly safe"
    elif i<=50:
        return "Minor Threat"
    elif i<=100:
        return "Mild Threat"
    elif i<=200:
        return "Moderate Threat"
    elif i<=350:
        return "Significant Threat"
    elif i<=550:
        return "Major Threat"
    else:
        return "Severe Threat"